package com.imran.practical.dto;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.validation.constraints.Size;

import com.sun.istack.NotNull;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@Entity
@ApiModel(description = "This is categories entity you can add categories ")
public class Category
{
	@Id
	@GeneratedValue
	@ApiModelProperty(notes = "Id is autogenerated, please dont spend you valuable time on provideing you own id ")
	private int id;
	
	@Size(min = 2, max = 10)
	@ApiModelProperty(notes = "name should contain at least 2 letter and atmost 10 letter")
	private String name;
	
	@NotNull
	@ApiModelProperty(notes = "description shouldn't empty, let you finger pain and scratch you brain to provide description of categories")
	private String description;
}
